stages:
  - test

.test:
    script:
        - python setup.py install
        - python -m pytest

verify-3.6:
    extends: .test
    stage: test
    image: python:3.6

verify-2.7:
    extends: .test
    stage: test
    image: python:2.7

