stages:
  - test

test_3.6:
    stage: test
    image: python:3.6
    script:
        - python setup.py install
        - pip install pytest
        - python -m pytest

test_2.7:
    stage: test
    image: python:2.7
    script:
        - python setup.py install
        - pip install pytest
        - python -m pytest


