{% set name = "mechkit" %}
{% set version = "0.1.211" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d82fb957f6ba39183441de64ed905023f5986434e6adcadcdcf703f4824d9889

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pip
    - python
  run:
    - numpy
    - python

test:
  imports:
    - mechkit

about:
  home: "https://github.com/JulianKarlBauer/mechkit"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Basic continuum mechanics toolkit"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
