{% set name = "mechkit" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "69b567a1fb272b5f54fa7d068d2d16445ee435e53c91d368489fe1df7151383e"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - numpy
    - pip
    - python
  run:
    - numpy
    - python

test:
  imports:
    - mechkit

about:
  home: "https://github.com/JulianKarlBauer/mechkit"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "Basic continuum mechanics toolkit"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
