{% set name = "mechkit" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7d0ef6f67fd52eca9b1d32b786be04c02400766d19e7a9920159ab7a76688139

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pip
    - python
  run:
    - numpy
    - python

test:
  imports:
    - mechkit

about:
  home: "https://github.com/JulianKarlBauer/mechkit"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Basic continuum mechanics toolkit"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
