{% set name = "mechkit" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f2a79e5dcea7a444e6e42438d8e4c4d767225a3c18e09271b5f1ec2913c4c4cc

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pip
    - python
  run:
    - numpy
    - python

test:
  imports:
    - mechkit

about:
  home: "https://github.com/JulianKarlBauer/mechkit"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Basic continuum mechanics toolkit"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
