{% set name = "mechkit" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "b14d3117f794a0bceffd281c6bc73a19c33c7479e4b28f5aa4bd804e9b01e4dd"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - numpy
    - pip
    - python
  run:
    - numpy
    - python

test:
  imports:
    - mechkit

about:
  home: "https://github.com/JulianBauerKIT/mechkit"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "Basic tools for continuum mechanics using numpy"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
